version: '3.9'

services:

  db:
    image: postgres:16
    container_name: todo_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: todo_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: todo_web #my custom app container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app #mounts the current directory to /app in the container, allowing live code changes without rebuilding
    ports:
      - "8000:8000"
    env_file:
      - .env #loads environment variables from the .env file into the container, making them accessible to the Django app
    depends_on: #ensures that the web service starts only after the db and redis services are up and running, preventing connection issues when the Django app tries to access the database or Redis.
      - db
      - redis

  celery:
    build: .
    container_name: todo_celery
    command: celery -A config worker --loglevel=info #starts the celery worker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis



  celery-beat:
    build: .
    container_name: todo_celery_beat
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
volumes:
  postgres_data:     