### Create a todo
POST http://localhost:8000/api/todos/
Content-Type: application/json

{
  "title": "study jwt authentiction",
  "description": "athentication, authorization",
  "priority": "high"
}

### List all todos
GET http://localhost:8000/api/todos/

### Toggle completed
PATCH http://localhost:8000/api/todos/5/toggle/

### Delete
DELETE http://localhost:8000/api/todos/4/